//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BWalletService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BWalletSetting", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Wallet")]
    public partial class BWalletSetting : object
    {
        
        private BWalletService.Environment EnvironmentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BWalletService.Environment Environment
        {
            get
            {
                return this.EnvironmentField;
            }
            set
            {
                this.EnvironmentField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Environment", Namespace="http://schemas.datacontract.org/2004/07/FHCore.API.Core")]
    public enum Environment : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PRIVATENET = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAINNET = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TESTNET = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BWalletSetResult", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Wallet")]
    public partial class BWalletSetResult : object
    {
        
        private BWalletService.Status StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BWalletService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Misc")]
    public partial class Status : object
    {
        
        private int CodeField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BWalletGetMnemonicResult", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Wallet")]
    public partial class BWalletGetMnemonicResult : object
    {
        
        private string MnemonicField;
        
        private BWalletService.Status StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mnemonic
        {
            get
            {
                return this.MnemonicField;
            }
            set
            {
                this.MnemonicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BWalletService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BWalletGetAccountResult", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Wallet")]
    public partial class BWalletGetAccountResult : object
    {
        
        private string AddressField;
        
        private string PrivateKeyField;
        
        private BWalletService.Status StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrivateKey
        {
            get
            {
                return this.PrivateKeyField;
            }
            set
            {
                this.PrivateKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BWalletService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BWalletService.IBWallet")]
    public interface IBWallet
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWallet/Set", ReplyAction="http://tempuri.org/IBWallet/SetResponse")]
        System.Threading.Tasks.Task<BWalletService.BWalletSetResult> SetAsync(string authenticatedToken, BWalletService.BWalletSetting setting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWallet/GetMnemonic", ReplyAction="http://tempuri.org/IBWallet/GetMnemonicResponse")]
        System.Threading.Tasks.Task<BWalletService.BWalletGetMnemonicResult> GetMnemonicAsync(string authenticatedToken, string wordList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBWallet/GetAccount", ReplyAction="http://tempuri.org/IBWallet/GetAccountResponse")]
        System.Threading.Tasks.Task<BWalletService.BWalletGetAccountResult> GetAccountAsync(string authenticatedToken, string mnemonic, int index);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IBWalletChannel : BWalletService.IBWallet, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class BWalletClient : System.ServiceModel.ClientBase<BWalletService.IBWallet>, BWalletService.IBWallet
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BWalletClient() : 
                base(BWalletClient.GetDefaultBinding(), BWalletClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IBWallet.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BWalletClient(EndpointConfiguration endpointConfiguration) : 
                base(BWalletClient.GetBindingForEndpoint(endpointConfiguration), BWalletClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BWalletClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BWalletClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BWalletClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BWalletClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BWalletClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<BWalletService.BWalletSetResult> SetAsync(string authenticatedToken, BWalletService.BWalletSetting setting)
        {
            return base.Channel.SetAsync(authenticatedToken, setting);
        }
        
        public System.Threading.Tasks.Task<BWalletService.BWalletGetMnemonicResult> GetMnemonicAsync(string authenticatedToken, string wordList)
        {
            return base.Channel.GetMnemonicAsync(authenticatedToken, wordList);
        }
        
        public System.Threading.Tasks.Task<BWalletService.BWalletGetAccountResult> GetAccountAsync(string authenticatedToken, string mnemonic, int index)
        {
            return base.Channel.GetAccountAsync(authenticatedToken, mnemonic, index);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBWallet))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBWallet))
            {
                return new System.ServiceModel.EndpointAddress("http://api.famhopperchain.com/Wallet/BWallet.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BWalletClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IBWallet);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BWalletClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IBWallet);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IBWallet,
        }
    }
}
