//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailEnqueueResult", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Message")]
    public partial class EmailEnqueueResult : object
    {
        
        private EmailService.Status StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmailService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Misc")]
    public partial class Status : object
    {
        
        private int CodeField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailDequeueResult", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Message")]
    public partial class EmailDequeueResult : object
    {
        
        private EmailService.EmailResult EmailResultField;
        
        private EmailService.SMTPResult[] SMTPResultsField;
        
        private EmailService.Status StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmailService.EmailResult EmailResult
        {
            get
            {
                return this.EmailResultField;
            }
            set
            {
                this.EmailResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmailService.SMTPResult[] SMTPResults
        {
            get
            {
                return this.SMTPResultsField;
            }
            set
            {
                this.SMTPResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmailService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailResult", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Message")]
    public partial class EmailResult : object
    {
        
        private string BccEmailsField;
        
        private string BodyField;
        
        private string CcEmailsField;
        
        private System.DateTime CreatedDateField;
        
        private string FromEmailField;
        
        private int IdField;
        
        private bool IsBulkedField;
        
        private bool IsHtmlField;
        
        private System.Nullable<System.DateTime> ProcessedDateField;
        
        private int ServerIdField;
        
        private EmailService.ServerResult ServerResultField;
        
        private System.Nullable<bool> StatusField;
        
        private string SubjectField;
        
        private string ToEmailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BccEmails
        {
            get
            {
                return this.BccEmailsField;
            }
            set
            {
                this.BccEmailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CcEmails
        {
            get
            {
                return this.CcEmailsField;
            }
            set
            {
                this.CcEmailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate
        {
            get
            {
                return this.CreatedDateField;
            }
            set
            {
                this.CreatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromEmail
        {
            get
            {
                return this.FromEmailField;
            }
            set
            {
                this.FromEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBulked
        {
            get
            {
                return this.IsBulkedField;
            }
            set
            {
                this.IsBulkedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHtml
        {
            get
            {
                return this.IsHtmlField;
            }
            set
            {
                this.IsHtmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ProcessedDate
        {
            get
            {
                return this.ProcessedDateField;
            }
            set
            {
                this.ProcessedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServerId
        {
            get
            {
                return this.ServerIdField;
            }
            set
            {
                this.ServerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmailService.ServerResult ServerResult
        {
            get
            {
                return this.ServerResultField;
            }
            set
            {
                this.ServerResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToEmails
        {
            get
            {
                return this.ToEmailsField;
            }
            set
            {
                this.ToEmailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMTPResult", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Message")]
    public partial class SMTPResult : object
    {
        
        private string HostField;
        
        private int IdField;
        
        private bool IsBulkedField;
        
        private bool IsSSLEnabledField;
        
        private string NameField;
        
        private string PasswordField;
        
        private int PortField;
        
        private int PriorityField;
        
        private int ServerIdField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Host
        {
            get
            {
                return this.HostField;
            }
            set
            {
                this.HostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBulked
        {
            get
            {
                return this.IsBulkedField;
            }
            set
            {
                this.IsBulkedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSSLEnabled
        {
            get
            {
                return this.IsSSLEnabledField;
            }
            set
            {
                this.IsSSLEnabledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Port
        {
            get
            {
                return this.PortField;
            }
            set
            {
                this.PortField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServerId
        {
            get
            {
                return this.ServerIdField;
            }
            set
            {
                this.ServerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerResult", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Message")]
    public partial class ServerResult : object
    {
        
        private int IdField;
        
        private string IpAddressField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpAddress
        {
            get
            {
                return this.IpAddressField;
            }
            set
            {
                this.IpAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailDispatchedResult", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Message")]
    public partial class EmailDispatchedResult : object
    {
        
        private EmailService.Status StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EmailService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailService.IEmail")]
    public interface IEmail
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/Enqueue", ReplyAction="http://tempuri.org/IEmail/EnqueueResponse")]
        System.Threading.Tasks.Task<EmailService.EmailEnqueueResult> EnqueueAsync(string authenticatedToken, string subject, string body, string toEmails, string ccEmails, string bccEmails, bool isBulked);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/Dequeue", ReplyAction="http://tempuri.org/IEmail/DequeueResponse")]
        System.Threading.Tasks.Task<EmailService.EmailDequeueResult> DequeueAsync(string authenticatedToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmail/Dispatched", ReplyAction="http://tempuri.org/IEmail/DispatchedResponse")]
        System.Threading.Tasks.Task<EmailService.EmailDispatchedResult> DispatchedAsync(string authenticatedToken, int emailId, int smtpId, bool status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IEmailChannel : EmailService.IEmail, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class EmailClient : System.ServiceModel.ClientBase<EmailService.IEmail>, EmailService.IEmail
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EmailClient() : 
                base(EmailClient.GetDefaultBinding(), EmailClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IEmail.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmailClient(EndpointConfiguration endpointConfiguration) : 
                base(EmailClient.GetBindingForEndpoint(endpointConfiguration), EmailClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmailClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EmailClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmailClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EmailClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<EmailService.EmailEnqueueResult> EnqueueAsync(string authenticatedToken, string subject, string body, string toEmails, string ccEmails, string bccEmails, bool isBulked)
        {
            return base.Channel.EnqueueAsync(authenticatedToken, subject, body, toEmails, ccEmails, bccEmails, isBulked);
        }
        
        public System.Threading.Tasks.Task<EmailService.EmailDequeueResult> DequeueAsync(string authenticatedToken)
        {
            return base.Channel.DequeueAsync(authenticatedToken);
        }
        
        public System.Threading.Tasks.Task<EmailService.EmailDispatchedResult> DispatchedAsync(string authenticatedToken, int emailId, int smtpId, bool status)
        {
            return base.Channel.DispatchedAsync(authenticatedToken, emailId, smtpId, status);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEmail))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEmail))
            {
                return new System.ServiceModel.EndpointAddress("http://202.53.150.20/Message/Email.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EmailClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IEmail);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EmailClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IEmail);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IEmail,
        }
    }
}
