//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTransactionService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BTransactionSetting", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Transaction")]
    public partial class BTransactionSetting : object
    {
        
        private BTransactionService.Environment EnvironmentField;
        
        private BTransactionService.Platform PlatformField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BTransactionService.Environment Environment
        {
            get
            {
                return this.EnvironmentField;
            }
            set
            {
                this.EnvironmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BTransactionService.Platform Platform
        {
            get
            {
                return this.PlatformField;
            }
            set
            {
                this.PlatformField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Environment", Namespace="http://schemas.datacontract.org/2004/07/FHCore.API.Core")]
    public enum Environment : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PRIVATENET = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAINNET = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TESTNET = 0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Platform", Namespace="http://schemas.datacontract.org/2004/07/FHCore.API.Core")]
    public enum Platform : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BTC = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NEO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ETH = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BTransactionSetResult", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Transaction")]
    public partial class BTransactionSetResult : object
    {
        
        private BTransactionService.Status StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BTransactionService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Misc")]
    public partial class Status : object
    {
        
        private int CodeField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BTransactionRetrieveResult", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Transaction")]
    public partial class BTransactionRetrieveResult : object
    {
        
        private BTransactionService.Status StatusField;
        
        private BTransactionService.BTransaction[] TransactionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BTransactionService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BTransactionService.BTransaction[] Transactions
        {
            get
            {
                return this.TransactionsField;
            }
            set
            {
                this.TransactionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BTransaction", Namespace="http://schemas.datacontract.org/2004/07/FHCore.Domain")]
    public partial class BTransaction : BTransactionService.Entity
    {
        
        private string BlockHashField;
        
        private int BlockNumberField;
        
        private int ConfirmationsField;
        
        private decimal FeeField;
        
        private BTransactionService.BTransactionVIn[] FromField;
        
        private int IdField;
        
        private BTransactionService.BTransactionVOut[] ToField;
        
        private string TxHashIdField;
        
        private decimal ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlockHash
        {
            get
            {
                return this.BlockHashField;
            }
            set
            {
                this.BlockHashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BlockNumber
        {
            get
            {
                return this.BlockNumberField;
            }
            set
            {
                this.BlockNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Confirmations
        {
            get
            {
                return this.ConfirmationsField;
            }
            set
            {
                this.ConfirmationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Fee
        {
            get
            {
                return this.FeeField;
            }
            set
            {
                this.FeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BTransactionService.BTransactionVIn[] From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BTransactionService.BTransactionVOut[] To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxHashId
        {
            get
            {
                return this.TxHashIdField;
            }
            set
            {
                this.TxHashIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entity", Namespace="http://schemas.datacontract.org/2004/07/FHCore.Common.Models")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BTransactionService.BTransactionVIn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BTransactionService.BTransactionVOut))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BTransactionService.BTransaction))]
    public partial class Entity : object
    {
        
        private BTransactionService.ObjectState ObjectStateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BTransactionService.ObjectState ObjectState
        {
            get
            {
                return this.ObjectStateField;
            }
            set
            {
                this.ObjectStateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BTransactionVIn", Namespace="http://schemas.datacontract.org/2004/07/FHCore.Domain")]
    public partial class BTransactionVIn : BTransactionService.Entity
    {
        
        private string AddressField;
        
        private BTransactionService.BTransaction BTransactionField;
        
        private string CoinbaseField;
        
        private int IdField;
        
        private string TxHashIdField;
        
        private decimal ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BTransactionService.BTransaction BTransaction
        {
            get
            {
                return this.BTransactionField;
            }
            set
            {
                this.BTransactionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Coinbase
        {
            get
            {
                return this.CoinbaseField;
            }
            set
            {
                this.CoinbaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxHashId
        {
            get
            {
                return this.TxHashIdField;
            }
            set
            {
                this.TxHashIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BTransactionVOut", Namespace="http://schemas.datacontract.org/2004/07/FHCore.Domain")]
    public partial class BTransactionVOut : BTransactionService.Entity
    {
        
        private string AddressField;
        
        private BTransactionService.BTransaction BTransactionField;
        
        private int IdField;
        
        private string SpentTxHashIdField;
        
        private decimal ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BTransactionService.BTransaction BTransaction
        {
            get
            {
                return this.BTransactionField;
            }
            set
            {
                this.BTransactionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpentTxHashId
        {
            get
            {
                return this.SpentTxHashIdField;
            }
            set
            {
                this.SpentTxHashIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectState", Namespace="http://schemas.datacontract.org/2004/07/FHCore.Common.Enums")]
    public enum ObjectState : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BTransactionDetailRetrieveResult", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Transaction")]
    public partial class BTransactionDetailRetrieveResult : object
    {
        
        private string BlockHashField;
        
        private int BlockNumberField;
        
        private decimal ConfirmationsField;
        
        private decimal FeeField;
        
        private BTransactionService.BTransactionVIn[] FromField;
        
        private BTransactionService.Status StatusField;
        
        private BTransactionService.BTransactionVOut[] ToField;
        
        private string TxHashIdField;
        
        private decimal ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlockHash
        {
            get
            {
                return this.BlockHashField;
            }
            set
            {
                this.BlockHashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BlockNumber
        {
            get
            {
                return this.BlockNumberField;
            }
            set
            {
                this.BlockNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Confirmations
        {
            get
            {
                return this.ConfirmationsField;
            }
            set
            {
                this.ConfirmationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Fee
        {
            get
            {
                return this.FeeField;
            }
            set
            {
                this.FeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BTransactionService.BTransactionVIn[] From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BTransactionService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BTransactionService.BTransactionVOut[] To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxHashId
        {
            get
            {
                return this.TxHashIdField;
            }
            set
            {
                this.TxHashIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BTransactionService.IBTransaction")]
    public interface IBTransaction
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBTransaction/Set", ReplyAction="http://tempuri.org/IBTransaction/SetResponse")]
        System.Threading.Tasks.Task<BTransactionService.BTransactionSetResult> SetAsync(string authenticatedToken, BTransactionService.BTransactionSetting setting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBTransaction/RetrieveTransactions", ReplyAction="http://tempuri.org/IBTransaction/RetrieveTransactionsResponse")]
        System.Threading.Tasks.Task<BTransactionService.BTransactionRetrieveResult> RetrieveTransactionsAsync(string authenticatedToken, string address, int fromBlockNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBTransaction/RetrieveTransactionDetail", ReplyAction="http://tempuri.org/IBTransaction/RetrieveTransactionDetailResponse")]
        System.Threading.Tasks.Task<BTransactionService.BTransactionDetailRetrieveResult> RetrieveTransactionDetailAsync(string authenticatedToken, string txHashId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IBTransactionChannel : BTransactionService.IBTransaction, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class BTransactionClient : System.ServiceModel.ClientBase<BTransactionService.IBTransaction>, BTransactionService.IBTransaction
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BTransactionClient() : 
                base(BTransactionClient.GetDefaultBinding(), BTransactionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IBTransaction.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BTransactionClient(EndpointConfiguration endpointConfiguration) : 
                base(BTransactionClient.GetBindingForEndpoint(endpointConfiguration), BTransactionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BTransactionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BTransactionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BTransactionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BTransactionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BTransactionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<BTransactionService.BTransactionSetResult> SetAsync(string authenticatedToken, BTransactionService.BTransactionSetting setting)
        {
            return base.Channel.SetAsync(authenticatedToken, setting);
        }
        
        public System.Threading.Tasks.Task<BTransactionService.BTransactionRetrieveResult> RetrieveTransactionsAsync(string authenticatedToken, string address, int fromBlockNumber)
        {
            return base.Channel.RetrieveTransactionsAsync(authenticatedToken, address, fromBlockNumber);
        }
        
        public System.Threading.Tasks.Task<BTransactionService.BTransactionDetailRetrieveResult> RetrieveTransactionDetailAsync(string authenticatedToken, string txHashId)
        {
            return base.Channel.RetrieveTransactionDetailAsync(authenticatedToken, txHashId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBTransaction))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBTransaction))
            {
                return new System.ServiceModel.EndpointAddress("http://api.famhopperchain.com/Transaction/BTransaction.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BTransactionClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IBTransaction);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BTransactionClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IBTransaction);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IBTransaction,
        }
    }
}
