//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETransactionService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETransactionSetting", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Transaction")]
    public partial class ETransactionSetting : object
    {
        
        private string ApiKeyField;
        
        private ETransactionService.Environment EnvironmentField;
        
        private ETransactionService.Platform PlatformField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApiKey
        {
            get
            {
                return this.ApiKeyField;
            }
            set
            {
                this.ApiKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ETransactionService.Environment Environment
        {
            get
            {
                return this.EnvironmentField;
            }
            set
            {
                this.EnvironmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ETransactionService.Platform Platform
        {
            get
            {
                return this.PlatformField;
            }
            set
            {
                this.PlatformField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Environment", Namespace="http://schemas.datacontract.org/2004/07/FHCore.API.Core")]
    public enum Environment : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PRIVATENET = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAINNET = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TESTNET = 0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Platform", Namespace="http://schemas.datacontract.org/2004/07/FHCore.API.Core")]
    public enum Platform : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BTC = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NEO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ETH = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETransactionSetResult", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Transaction")]
    public partial class ETransactionSetResult : object
    {
        
        private ETransactionService.Status StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ETransactionService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Misc")]
    public partial class Status : object
    {
        
        private int CodeField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETransactionRetrieveResult", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Transaction")]
    public partial class ETransactionRetrieveResult : object
    {
        
        private ETransactionService.Status StatusField;
        
        private ETransactionService.ETransaction[] TransactionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ETransactionService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ETransactionService.ETransaction[] Transactions
        {
            get
            {
                return this.TransactionsField;
            }
            set
            {
                this.TransactionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETransaction", Namespace="http://schemas.datacontract.org/2004/07/FHCore.Domain")]
    public partial class ETransaction : ETransactionService.Entity
    {
        
        private string BlockHashField;
        
        private int BlockNumberField;
        
        private string FromAddressField;
        
        private decimal GasField;
        
        private decimal GasPriceField;
        
        private int IdField;
        
        private System.Nullable<bool> StatusField;
        
        private string ToAddressField;
        
        private string TxHashIdField;
        
        private decimal ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlockHash
        {
            get
            {
                return this.BlockHashField;
            }
            set
            {
                this.BlockHashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BlockNumber
        {
            get
            {
                return this.BlockNumberField;
            }
            set
            {
                this.BlockNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromAddress
        {
            get
            {
                return this.FromAddressField;
            }
            set
            {
                this.FromAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Gas
        {
            get
            {
                return this.GasField;
            }
            set
            {
                this.GasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GasPrice
        {
            get
            {
                return this.GasPriceField;
            }
            set
            {
                this.GasPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToAddress
        {
            get
            {
                return this.ToAddressField;
            }
            set
            {
                this.ToAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxHashId
        {
            get
            {
                return this.TxHashIdField;
            }
            set
            {
                this.TxHashIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entity", Namespace="http://schemas.datacontract.org/2004/07/FHCore.Common.Models")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ETransactionService.ETransaction))]
    public partial class Entity : object
    {
        
        private ETransactionService.ObjectState ObjectStateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ETransactionService.ObjectState ObjectState
        {
            get
            {
                return this.ObjectStateField;
            }
            set
            {
                this.ObjectStateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectState", Namespace="http://schemas.datacontract.org/2004/07/FHCore.Common.Enums")]
    public enum ObjectState : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETransactionStatusRetrieveResult", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Transaction")]
    public partial class ETransactionStatusRetrieveResult : object
    {
        
        private System.Nullable<bool> ReceiptField;
        
        private ETransactionService.Status StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Receipt
        {
            get
            {
                return this.ReceiptField;
            }
            set
            {
                this.ReceiptField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ETransactionService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ETransactionService.IETransaction")]
    public interface IETransaction
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IETransaction/Set", ReplyAction="http://tempuri.org/IETransaction/SetResponse")]
        System.Threading.Tasks.Task<ETransactionService.ETransactionSetResult> SetAsync(string authenticatedToken, ETransactionService.ETransactionSetting setting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IETransaction/RetrieveTransactions", ReplyAction="http://tempuri.org/IETransaction/RetrieveTransactionsResponse")]
        System.Threading.Tasks.Task<ETransactionService.ETransactionRetrieveResult> RetrieveTransactionsAsync(string authenticatedToken, string address, int fromBlockNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IETransaction/GetTransactionStatus", ReplyAction="http://tempuri.org/IETransaction/GetTransactionStatusResponse")]
        System.Threading.Tasks.Task<ETransactionService.ETransactionStatusRetrieveResult> GetTransactionStatusAsync(string authenticatedToken, string txHashId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IETransactionChannel : ETransactionService.IETransaction, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class ETransactionClient : System.ServiceModel.ClientBase<ETransactionService.IETransaction>, ETransactionService.IETransaction
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ETransactionClient() : 
                base(ETransactionClient.GetDefaultBinding(), ETransactionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IETransaction.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ETransactionClient(EndpointConfiguration endpointConfiguration) : 
                base(ETransactionClient.GetBindingForEndpoint(endpointConfiguration), ETransactionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ETransactionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ETransactionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ETransactionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ETransactionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ETransactionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ETransactionService.ETransactionSetResult> SetAsync(string authenticatedToken, ETransactionService.ETransactionSetting setting)
        {
            return base.Channel.SetAsync(authenticatedToken, setting);
        }
        
        public System.Threading.Tasks.Task<ETransactionService.ETransactionRetrieveResult> RetrieveTransactionsAsync(string authenticatedToken, string address, int fromBlockNumber)
        {
            return base.Channel.RetrieveTransactionsAsync(authenticatedToken, address, fromBlockNumber);
        }
        
        public System.Threading.Tasks.Task<ETransactionService.ETransactionStatusRetrieveResult> GetTransactionStatusAsync(string authenticatedToken, string txHashId)
        {
            return base.Channel.GetTransactionStatusAsync(authenticatedToken, txHashId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IETransaction))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IETransaction))
            {
                return new System.ServiceModel.EndpointAddress("http://api.famhopperchain.com/Transaction/ETransaction.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ETransactionClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IETransaction);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ETransactionClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IETransaction);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IETransaction,
        }
    }
}
