//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWalletService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EWalletSetting", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Wallet")]
    public partial class EWalletSetting : object
    {
        
        private EWalletService.Environment EnvironmentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EWalletService.Environment Environment
        {
            get
            {
                return this.EnvironmentField;
            }
            set
            {
                this.EnvironmentField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Environment", Namespace="http://schemas.datacontract.org/2004/07/FHCore.API.Core")]
    public enum Environment : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PRIVATENET = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAINNET = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TESTNET = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EWalletSetResult", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Wallet")]
    public partial class EWalletSetResult : object
    {
        
        private EWalletService.Status StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EWalletService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Misc")]
    public partial class Status : object
    {
        
        private int CodeField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EWalletGetMnemonicResult", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Wallet")]
    public partial class EWalletGetMnemonicResult : object
    {
        
        private string MnemonicField;
        
        private EWalletService.Status StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mnemonic
        {
            get
            {
                return this.MnemonicField;
            }
            set
            {
                this.MnemonicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EWalletService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EWalletGetAccountResult", Namespace="http://schemas.datacontract.org/2004/07/FHCore.WCF.Wallet")]
    public partial class EWalletGetAccountResult : object
    {
        
        private string AddressField;
        
        private string PrivateKeyField;
        
        private EWalletService.Status StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrivateKey
        {
            get
            {
                return this.PrivateKeyField;
            }
            set
            {
                this.PrivateKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EWalletService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EWalletService.IEWallet")]
    public interface IEWallet
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWallet/Set", ReplyAction="http://tempuri.org/IEWallet/SetResponse")]
        System.Threading.Tasks.Task<EWalletService.EWalletSetResult> SetAsync(string authenticatedToken, EWalletService.EWalletSetting setting);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWallet/GetMnemonic", ReplyAction="http://tempuri.org/IEWallet/GetMnemonicResponse")]
        System.Threading.Tasks.Task<EWalletService.EWalletGetMnemonicResult> GetMnemonicAsync(string authenticatedToken, string wordList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEWallet/GetAccount", ReplyAction="http://tempuri.org/IEWallet/GetAccountResponse")]
        System.Threading.Tasks.Task<EWalletService.EWalletGetAccountResult> GetAccountAsync(string authenticatedToken, string mnemonic, int index);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IEWalletChannel : EWalletService.IEWallet, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class EWalletClient : System.ServiceModel.ClientBase<EWalletService.IEWallet>, EWalletService.IEWallet
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EWalletClient() : 
                base(EWalletClient.GetDefaultBinding(), EWalletClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IEWallet.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EWalletClient(EndpointConfiguration endpointConfiguration) : 
                base(EWalletClient.GetBindingForEndpoint(endpointConfiguration), EWalletClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EWalletClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EWalletClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EWalletClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EWalletClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EWalletClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<EWalletService.EWalletSetResult> SetAsync(string authenticatedToken, EWalletService.EWalletSetting setting)
        {
            return base.Channel.SetAsync(authenticatedToken, setting);
        }
        
        public System.Threading.Tasks.Task<EWalletService.EWalletGetMnemonicResult> GetMnemonicAsync(string authenticatedToken, string wordList)
        {
            return base.Channel.GetMnemonicAsync(authenticatedToken, wordList);
        }
        
        public System.Threading.Tasks.Task<EWalletService.EWalletGetAccountResult> GetAccountAsync(string authenticatedToken, string mnemonic, int index)
        {
            return base.Channel.GetAccountAsync(authenticatedToken, mnemonic, index);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEWallet))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEWallet))
            {
                return new System.ServiceModel.EndpointAddress("http://api.famhopperchain.com/Wallet/EWallet.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EWalletClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IEWallet);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EWalletClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IEWallet);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IEWallet,
        }
    }
}
