Use CPL;
INSERT INTO MobileLangDetail VALUES (1, N'ContactScreen_Button_Submit', N'Submit');INSERT INTO MobileLangDetail VALUES(2, N'ContactScreen_Button_Submit', N'提出する');
INSERT INTO MobileLangDetail VALUES (1, N'ContactScreen_Dialog_Deposit_Title', N'Deposit');INSERT INTO MobileLangDetail VALUES(2, N'ContactScreen_Dialog_Deposit_Title', N'入金');
INSERT INTO MobileLangDetail VALUES (1, N'ContactScreen_Dialog_KYC_Title', N'KYC');INSERT INTO MobileLangDetail VALUES(2, N'ContactScreen_Dialog_KYC_Title', N'KYC');
INSERT INTO MobileLangDetail VALUES (1, N'ContactScreen_Dialog_Lottery_Title', N'Lottery');INSERT INTO MobileLangDetail VALUES(2, N'ContactScreen_Dialog_Lottery_Title', N'宝くじ');
INSERT INTO MobileLangDetail VALUES (1, N'ContactScreen_Dialog_Other_Title', N'Other');INSERT INTO MobileLangDetail VALUES(2, N'ContactScreen_Dialog_Other_Title', N'その他');
INSERT INTO MobileLangDetail VALUES (1, N'ContactScreen_Dialog_Success_Description', N'Thank you for contact my team, we will send feed back for you in early time!');INSERT INTO MobileLangDetail VALUES(2, N'ContactScreen_Dialog_Success_Description', N'連絡していただきありがとうございます、早い時期にフィードバックをお送りいたします！');
INSERT INTO MobileLangDetail VALUES (1, N'ContactScreen_Dialog_Withdraw_Title', N'Withdraw');INSERT INTO MobileLangDetail VALUES(2, N'ContactScreen_Dialog_Withdraw_Title', N'出金');
INSERT INTO MobileLangDetail VALUES (1, N'ContactScreen_Email_Sent_Successfully', N'Email is sent successfully');INSERT INTO MobileLangDetail VALUES(2, N'ContactScreen_Email_Sent_Successfully', N'イメールが正常に送信されました');
INSERT INTO MobileLangDetail VALUES (1, N'ContactScreen_Form_Title', N'Ask us anything');INSERT INTO MobileLangDetail VALUES(2, N'ContactScreen_Form_Title', N'質問ありますか？');
INSERT INTO MobileLangDetail VALUES (1, N'ContactScreen_Input_Category_Placeholder', N'Category');INSERT INTO MobileLangDetail VALUES(2, N'ContactScreen_Input_Category_Placeholder', N'カテゴリー');
INSERT INTO MobileLangDetail VALUES (1, N'ContactScreen_Input_Description_PlaceHolder', N'Description');INSERT INTO MobileLangDetail VALUES(2, N'ContactScreen_Input_Description_PlaceHolder', N'内容');
INSERT INTO MobileLangDetail VALUES (1, N'ContactScreen_Input_Email_PlaceHolder', N'Email');INSERT INTO MobileLangDetail VALUES(2, N'ContactScreen_Input_Email_PlaceHolder', N'イメール');
INSERT INTO MobileLangDetail VALUES (1, N'ContactScreen_Input_Subject_PlaceHolder', N'Subject');INSERT INTO MobileLangDetail VALUES(2, N'ContactScreen_Input_Subject_PlaceHolder', N'件名');
INSERT INTO MobileLangDetail VALUES (1, N'ContactScreen_Title', N'Contact');INSERT INTO MobileLangDetail VALUES(2, N'ContactScreen_Title', N'連絡先');
INSERT INTO MobileLangDetail VALUES (1, N'ContactScreen_Validate_Description', N'Please input description');INSERT INTO MobileLangDetail VALUES(2, N'ContactScreen_Validate_Description', N'内容を入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'ContactScreen_Validate_Email', N'Please input e-mail address');INSERT INTO MobileLangDetail VALUES(2, N'ContactScreen_Validate_Email', N'メールアドレスを入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'ContactScreen_Validate_Subject', N'Please input subject');INSERT INTO MobileLangDetail VALUES(2, N'ContactScreen_Validate_Subject', N'件名を入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'DepositAndWithdrawScreen_Insufficient_Funds', N'Insufficient funds');INSERT INTO MobileLangDetail VALUES(2, N'DepositAndWithdrawScreen_Insufficient_Funds', N'残高不足');
INSERT INTO MobileLangDetail VALUES (1, N'DepositAndWithdrawScreen_Invalid_BTCAddress', N'Invalid BTC address');INSERT INTO MobileLangDetail VALUES(2, N'DepositAndWithdrawScreen_Invalid_BTCAddress', N'無効なBTCアドレス');
INSERT INTO MobileLangDetail VALUES (1, N'DepositAndWithdrawScreen_Invalid_Withdraw_Amount', N'Invalid withdraw amount');INSERT INTO MobileLangDetail VALUES(2, N'DepositAndWithdrawScreen_Invalid_Withdraw_Amount', N'無効の引き出し金額');
INSERT INTO MobileLangDetail VALUES (1, N'DepositAndWithdrawScreen_Withdrawed_Successfully', N'Withdrawed successfully');INSERT INTO MobileLangDetail VALUES(2, N'DepositAndWithdrawScreen_Withdrawed_Successfully', N'撤収に成功しました');
INSERT INTO MobileLangDetail VALUES (1, N'DepositWithdrawScreen_Button_Deposit', N'Deposit');INSERT INTO MobileLangDetail VALUES(2, N'DepositWithdrawScreen_Button_Deposit', N'入金');
INSERT INTO MobileLangDetail VALUES (1, N'DepositWithdrawScreen_Button_Withdraw', N'Withdraw');INSERT INTO MobileLangDetail VALUES(2, N'DepositWithdrawScreen_Button_Withdraw', N'出金');
INSERT INTO MobileLangDetail VALUES (1, N'DepositWithdrawScreen_Title', N'Deposit/ Withdraw');INSERT INTO MobileLangDetail VALUES(2, N'DepositWithdrawScreen_Title', N'入金/出金');
INSERT INTO MobileLangDetail VALUES (1, N'DialogFinger_Button_Cancel', N'Cancel');INSERT INTO MobileLangDetail VALUES(2, N'DialogFinger_Button_Cancel', N'キャンセル');
INSERT INTO MobileLangDetail VALUES (1, N'DialogFinger_Content_Body', N'Unlock “Crypto Odds” with your fingerprint');INSERT INTO MobileLangDetail VALUES(2, N'DialogFinger_Content_Body', N'指紋で「Crypto Odds」のロックを解除する');
INSERT INTO MobileLangDetail VALUES (1, N'DialogFinger_Content_Head', N'Touch ID for “Crypto Odds”');INSERT INTO MobileLangDetail VALUES(2, N'DialogFinger_Content_Head', N'「Crypto Odds」のタッチID');
INSERT INTO MobileLangDetail VALUES (1, N'DialogFinger_Description_Authenticate', N'Scan your fingerprint on the device scanner to continue');INSERT INTO MobileLangDetail VALUES(2, N'DialogFinger_Description_Authenticate', N'デバイススキャナで指紋をスキャンして続行する');
INSERT INTO MobileLangDetail VALUES (1, N'EditEmailScreen_Button_Save', N'Save');INSERT INTO MobileLangDetail VALUES(2, N'EditEmailScreen_Button_Save', N'保存');
INSERT INTO MobileLangDetail VALUES (1, N'EditEmailScreen_Dialog_Success', N'Edit email successfully!');INSERT INTO MobileLangDetail VALUES(2, N'EditEmailScreen_Dialog_Success', N'イメールを正常に編集した！');
INSERT INTO MobileLangDetail VALUES (1, N'EditEmailScreen_Email_Updated_Successfully', N'Email updated successfully!');INSERT INTO MobileLangDetail VALUES(2, N'EditEmailScreen_Email_Updated_Successfully', N'イメールを正常に更新した！');
INSERT INTO MobileLangDetail VALUES (1, N'EditEmailScreen_Existing_Email', N'Email existing in system');INSERT INTO MobileLangDetail VALUES(2, N'EditEmailScreen_Existing_Email', N'システムに存在するイメール');
INSERT INTO MobileLangDetail VALUES (1, N'EditEmailScreen_Input_Confirm_Email_Placeholder', N'Confirm new email');INSERT INTO MobileLangDetail VALUES(2, N'EditEmailScreen_Input_Confirm_Email_Placeholder', N'新しいイメールを確認する');
INSERT INTO MobileLangDetail VALUES (1, N'EditEmailScreen_Input_Confirm_Password_Placeholder', N'Confirm password');INSERT INTO MobileLangDetail VALUES(2, N'EditEmailScreen_Input_Confirm_Password_Placeholder', N'パスワードを認証する');
INSERT INTO MobileLangDetail VALUES (1, N'EditEmailScreen_Input_New_Email_Placeholder', N'New email');INSERT INTO MobileLangDetail VALUES(2, N'EditEmailScreen_Input_New_Email_Placeholder', N'新しいイメール');
INSERT INTO MobileLangDetail VALUES (1, N'EditEmailScreen_Row_Current_Email_Title', N'Current email');INSERT INTO MobileLangDetail VALUES(2, N'EditEmailScreen_Row_Current_Email_Title', N'現在のイメール');
INSERT INTO MobileLangDetail VALUES (1, N'EditEmailScreen_Title', N'Edit Email');INSERT INTO MobileLangDetail VALUES(2, N'EditEmailScreen_Title', N'メールの編集');
INSERT INTO MobileLangDetail VALUES (1, N'EditEmailScreen_Validate_Email', N'Please input email address');INSERT INTO MobileLangDetail VALUES(2, N'EditEmailScreen_Validate_Email', N'イメールを入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'EditEmailScreen_Validate_Password', N'Please input confirm password');INSERT INTO MobileLangDetail VALUES(2, N'EditEmailScreen_Validate_Password', N'パスワードを入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'EditEmailScreen_Validate_Password_Not_Match', N'Password current not match');INSERT INTO MobileLangDetail VALUES(2, N'EditEmailScreen_Validate_Password_Not_Match', N'現在のパスワードと一致しない');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_Button_Save', N'Save');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_Button_Save', N'保存');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_Dialog_Error', N'Edit password fail!');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_Dialog_Error', N'パスワードの編集に失敗する！');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_Dialog_Success', N'Edit password successfully!');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_Dialog_Success', N'パスワードを正常に編集する！');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_Input_Confirm_Placeholder', N'Confirm password');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_Input_Confirm_Placeholder', N'パスワードを認証する');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_Input_Current_Placeholder', N'Current password');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_Input_Current_Placeholder', N'現在のパスワード');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_Input_New_Password_Placeholder', N'New password');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_Input_New_Password_Placeholder', N'新しいパスワード');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_Invalid_Current_Password', N'Invalid current password');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_Invalid_Current_Password', N'無効のパスワード');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_NonExisting_Account', N'Account is not existing');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_NonExisting_Account', N'アカウントは存在しません');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_Password_Updated_Successfully', N'Password is updated successfully');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_Password_Updated_Successfully', N'パスワードを正常に更新する！');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_Title', N'Edit Password');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_Title', N'パスワードの編集');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_Validate_Confirm_Not_Match', N'Password not match');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_Validate_Confirm_Not_Match', N'パスワードが一致しません');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_Validate_Confirm_Password', N'Please input confirm password');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_Validate_Confirm_Password', N'パスワードを入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_Validate_Current_Not_Match', N'Password current not match');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_Validate_Current_Not_Match', N'現在のパスワードと一致しない');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_Validate_Current_Password', N'Please input current password');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_Validate_Current_Password', N'現在のパスワードを入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_Validate_New_Password', N'Please input new password');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_Validate_New_Password', N'新しいパスワードを入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Birthday_Title', N'Date of birth');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Birthday_Title', N'生年月日');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Button_Close', N'Close');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Button_Close', N'閉じる');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Button_Save', N'Save');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Button_Save', N'保存');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Country_Title', N'Country');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Country_Title', N'国');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Dialog_Error', N'Edit profile fail!');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Dialog_Error', N'プロフィールを編集できません！');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Dialog_Success', N'Edit profile successfully!');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Dialog_Success', N'プロフィールを正常に編集する！');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Input_Address_Placeholder', N'Street address');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Input_Address_Placeholder', N'住所');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Input_City_Placeholder', N'City');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Input_City_Placeholder', N'都市');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Input_First_Name_Placeholder', N'First name');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Input_First_Name_Placeholder', N'	名');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Input_Last_Name_Placeholder', N'Last name');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Input_Last_Name_Placeholder', N'姓');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Input_Number_Phone_Placeholder', N'Phone number');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Input_Number_Phone_Placeholder', N'電話番号');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Input_Postal_Code_Placeholder', N'Postal code');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Input_Postal_Code_Placeholder', N'郵便番号');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Title', N'Edit Profile');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Title', N'プロファイル編集');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Validate_Address', N'Please input street address');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Validate_Address', N'住所を入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Validate_Birthday', N'Please choose date of birth');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Validate_Birthday', N'生年月日を入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Validate_City', N'Please input city');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Validate_City', N'都市を入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Validate_Country', N'Please choose country');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Validate_Country', N'国を選択してください');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Validate_First_Name', N'Please input first name');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Validate_First_Name', N'名前を入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Validate_Last_Name', N'Please input last name');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Validate_Last_Name', N'姓を入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Validate_Number_Phone', N'Please input phone number');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Validate_Number_Phone', N'電話番号を入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'EditProfileScreen_Validate_Postal_Code', N'Please input postal code');INSERT INTO MobileLangDetail VALUES(2, N'EditProfileScreen_Validate_Postal_Code', N'郵便番号を入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'KYCScreen_Button_Cancel', N'Cancel');INSERT INTO MobileLangDetail VALUES(2, N'KYCScreen_Button_Cancel', N'キャンセル');
INSERT INTO MobileLangDetail VALUES (1, N'KYCScreen_Button_Go_To_Web', N'Go to web');INSERT INTO MobileLangDetail VALUES(2, N'KYCScreen_Button_Go_To_Web', N'ウェブに行く');
INSERT INTO MobileLangDetail VALUES (1, N'KYCScreen_Dialog_Title', N'If you do not KYC for your account. Please touch "Go to Web" for update KYC');INSERT INTO MobileLangDetail VALUES(2, N'KYCScreen_Dialog_Title', N'あなたのアカウントにKYCがない場合、KYCを更新するには、[ウェブに行く]を押してください.');
INSERT INTO MobileLangDetail VALUES (1, N'MenuPincodeScreen_Button_Change', N'Change PIN Code');INSERT INTO MobileLangDetail VALUES(2, N'MenuPincodeScreen_Button_Change', N'PINコードの変更');
INSERT INTO MobileLangDetail VALUES (1, N'MenuPincodeScreen_Button_Remove', N'Remove PIN Code');INSERT INTO MobileLangDetail VALUES(2, N'MenuPincodeScreen_Button_Remove', N'PINコードを削除');
INSERT INTO MobileLangDetail VALUES (1, N'MenuPincodeScreen_Button_Setup', N'Setup PIN Code');INSERT INTO MobileLangDetail VALUES(2, N'MenuPincodeScreen_Button_Setup', N'PINコードの設定');
INSERT INTO MobileLangDetail VALUES (1, N'MenuPincodeScreen_Title', N'Setting Pincode');INSERT INTO MobileLangDetail VALUES(2, N'MenuPincodeScreen_Title', N'PINコードの設定');
INSERT INTO MobileLangDetail VALUES (1, N'MoreScreen_Button_Ok', N'OK');INSERT INTO MobileLangDetail VALUES(2, N'MoreScreen_Button_Ok', N'はい');
INSERT INTO MobileLangDetail VALUES (1, N'PincodeScreen_Button_Clear', N'Clear');INSERT INTO MobileLangDetail VALUES(2, N'PincodeScreen_Button_Clear', N'クリア');
INSERT INTO MobileLangDetail VALUES (1, N'PincodeScreen_Button_Delete', N'Delete');INSERT INTO MobileLangDetail VALUES(2, N'PincodeScreen_Button_Delete', N'削除');
INSERT INTO MobileLangDetail VALUES (1, N'PincodeScreen_Dialog_Message_Error', N'PIN code not match! Please re-input PIN code');INSERT INTO MobileLangDetail VALUES(2, N'PincodeScreen_Dialog_Message_Error', N'PINコードが一致しません！再入力してください！');
INSERT INTO MobileLangDetail VALUES (1, N'PincodeScreen_Dialog_Message_Success', N'Setting PIN code successfully!');INSERT INTO MobileLangDetail VALUES(2, N'PincodeScreen_Dialog_Message_Success', N'PINコードを正常に設定した。');
INSERT INTO MobileLangDetail VALUES (1, N'PincodeScreen_Input_Confirm_Title', N'Input confirm PIN code');INSERT INTO MobileLangDetail VALUES(2, N'PincodeScreen_Input_Confirm_Title', N'PINコードを確認する');
INSERT INTO MobileLangDetail VALUES (1, N'PincodeScreen_Input_Current_Title', N'Input current PIN code');INSERT INTO MobileLangDetail VALUES(2, N'PincodeScreen_Input_Current_Title', N'現在のPINコードを入力する');
INSERT INTO MobileLangDetail VALUES (1, N'PincodeScreen_Input_New_Title', N'Input new PIN code');INSERT INTO MobileLangDetail VALUES(2, N'PincodeScreen_Input_New_Title', N'新しいPINコードを入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'PincodeScreen_Title', N'Setting Pincode');INSERT INTO MobileLangDetail VALUES(2, N'PincodeScreen_Title', N'PINコードの設定');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileEditUserScreen_NonExisting_Account', N'Account is not existing');INSERT INTO MobileLangDetail VALUES(2, N'ProfileEditUserScreen_NonExisting_Account', N'アカウントは存在しません');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileEditUserScreen_Updated_Successfully', N'Personal info updated successfully');INSERT INTO MobileLangDetail VALUES(2, N'ProfileEditUserScreen_Updated_Successfully', N'個人情報を正常に更新しました。');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_Address_Title', N'Street address');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_Address_Title', N'住所');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_Birthday_Title', N'Date of birth');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_Birthday_Title', N'生年月日');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_BTC_Wallet_Title', N'BTC Wallet Address');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_BTC_Wallet_Title', N'BTCウォレットアドレス');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_Button_Edit', N'Edit');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_Button_Edit', N'編集');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_City_Title', N'City');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_City_Title', N'都市');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_Country_Title', N'Country');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_Country_Title', N'国');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_Email_Title', N'Email');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_Email_Title', N'イメール');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_ETH_Wallet_Title', N'ETH Wallet Address');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_ETH_Wallet_Title', N'ETHウォレットアドレス');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_First_Name_Title', N'First name');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_First_Name_Title', N'	名');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_Game_History_Title', N'Game history');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_Game_History_Title', N'ゲームの履歴');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_KYC_Status_Not_Verified', N'Not verified yet');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_KYC_Status_Not_Verified', N'確認されていない');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_KYC_Status_Verified', N'Verified');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_KYC_Status_Verified', N'検証済み');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_Last_Name_Title', N'Last name');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_Last_Name_Title', N'姓');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_Mobile_Title', N'Mobile');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_Mobile_Title', N'モバイル');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_Postal_Code_Title', N'Postal code');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_Postal_Code_Title', N'郵便番号');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_Title', N'Profile');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_Title', N'プロフィール');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_Transaction_Title', N'Transaction');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_Transaction_Title', N'トランザクション');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_Two_Factor_Status_Disable', N'Not enabled');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_Two_Factor_Status_Disable', N'無効');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_Two_Factor_Status_Enabled', N'Enabled');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_Two_Factor_Status_Enabled', N'有効');
INSERT INTO MobileLangDetail VALUES (1, N'ProfileScreen_Two_Factor_Title', N'Two-factor authentication');INSERT INTO MobileLangDetail VALUES(2, N'ProfileScreen_Two_Factor_Title', N'二要素認証');
INSERT INTO MobileLangDetail VALUES (1, N'PurchraseScreen_Validate_Max', N'The volume of CPL maximum is');INSERT INTO MobileLangDetail VALUES(2, N'PurchraseScreen_Validate_Max', N'CPLの最大量は');
INSERT INTO MobileLangDetail VALUES (1, N'PurchraseScreen_Validate_Min', N'The volume of CPL minimum is 1');INSERT INTO MobileLangDetail VALUES(2, N'PurchraseScreen_Validate_Min', N'CPLの最小量は1です');
INSERT INTO MobileLangDetail VALUES (1, N'PurchraseScreen_Validate_Null', N'Please input number of ticket');INSERT INTO MobileLangDetail VALUES(2, N'PurchraseScreen_Validate_Null', N'チケット数を入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'QrScanScreen_Dialog_Button_Cancel', N'Cancel');INSERT INTO MobileLangDetail VALUES(2, N'QrScanScreen_Dialog_Button_Cancel', N'キャンセル');
INSERT INTO MobileLangDetail VALUES (1, N'QrScanScreen_Dialog_Button_Ok', N'OK');INSERT INTO MobileLangDetail VALUES(2, N'QrScanScreen_Dialog_Button_Ok', N'はい');
INSERT INTO MobileLangDetail VALUES (1, N'QrScanScreen_Dialog_Permisson_Content', N'Crypto Odds Would like to Access the Camera');INSERT INTO MobileLangDetail VALUES(2, N'QrScanScreen_Dialog_Permisson_Content', N'「Crypto Odds」はカメラにアクセスしたい');
INSERT INTO MobileLangDetail VALUES (1, N'QrScanScreen_Dialog_Permisson_Content2', N'Please accept camera permission to scan QR code');INSERT INTO MobileLangDetail VALUES(2, N'QrScanScreen_Dialog_Permisson_Content2', N'QRコードをスキャンするためのカメラの許可をしてください');
INSERT INTO MobileLangDetail VALUES (1, N'QrScanScreen_Dialog_Permisson_Title', N'Permisson denied');INSERT INTO MobileLangDetail VALUES(2, N'QrScanScreen_Dialog_Permisson_Title', N'アクセス拒否');
INSERT INTO MobileLangDetail VALUES (1, N'QrScanScreen_Title', N'Qr Code Scanner');INSERT INTO MobileLangDetail VALUES(2, N'QrScanScreen_Title', N'QRコードスキャナ');
INSERT INTO MobileLangDetail VALUES (1, N'SecurityScreen_Button_Edit_Email', N'Edit email');INSERT INTO MobileLangDetail VALUES(2, N'SecurityScreen_Button_Edit_Email', N'イメールの編集');
INSERT INTO MobileLangDetail VALUES (1, N'SecurityScreen_Button_Edit_Password', N'Edit password');INSERT INTO MobileLangDetail VALUES(2, N'SecurityScreen_Button_Edit_Password', N'パスワードの編集');
INSERT INTO MobileLangDetail VALUES (1, N'SecurityScreen_Button_Fingerprint', N'Finger print');INSERT INTO MobileLangDetail VALUES(2, N'SecurityScreen_Button_Fingerprint', N'指紋');
INSERT INTO MobileLangDetail VALUES (1, N'SecurityScreen_Button_Pincode', N'PIN code');INSERT INTO MobileLangDetail VALUES(2, N'SecurityScreen_Button_Pincode', N'PINコード');
INSERT INTO MobileLangDetail VALUES (1, N'SecurityScreen_Title', N'Security');INSERT INTO MobileLangDetail VALUES(2, N'SecurityScreen_Title', N'セキュリティ');
INSERT INTO MobileLangDetail VALUES (1, N'SettingLanguageScreen_Title', N'Setting Language');INSERT INTO MobileLangDetail VALUES(2, N'SettingLanguageScreen_Title', N'言語の設定');
INSERT INTO MobileLangDetail VALUES (1, N'UserAccountScreen_Button_Profile', N'Profile');INSERT INTO MobileLangDetail VALUES(2, N'UserAccountScreen_Button_Profile', N'プロフィール');
INSERT INTO MobileLangDetail VALUES (1, N'UserAccountScreen_Button_Security', N'Security');INSERT INTO MobileLangDetail VALUES(2, N'UserAccountScreen_Button_Security', N'セキュリティ');
INSERT INTO MobileLangDetail VALUES (1, N'UserAccountScreen_Title', N'User Account');INSERT INTO MobileLangDetail VALUES(2, N'UserAccountScreen_Title', N'ユーザーアカウント');
INSERT INTO MobileLangDetail VALUES (1, N'WithdrawDialog_Button_Withdraw', N'Withdraw');INSERT INTO MobileLangDetail VALUES(2, N'WithdrawDialog_Button_Withdraw', N'出金');
INSERT INTO MobileLangDetail VALUES (1, N'WithdrawDialog_Input_Address_Title', N'Address');INSERT INTO MobileLangDetail VALUES(2, N'WithdrawDialog_Input_Address_Title', N'住所');
INSERT INTO MobileLangDetail VALUES (1, N'WithdrawDialog_Input_Amount_Title', N'Amount');INSERT INTO MobileLangDetail VALUES(2, N'WithdrawDialog_Input_Amount_Title', N'量');
INSERT INTO MobileLangDetail VALUES (1, N'WithdrawDialog_Input_Button_Max_Title', N'Max');INSERT INTO MobileLangDetail VALUES(2, N'WithdrawDialog_Input_Button_Max_Title', N'最大');
INSERT INTO MobileLangDetail VALUES (1, N'WithdrawDialog_Title', N'You are about to withdraw BTC from your account');INSERT INTO MobileLangDetail VALUES(2, N'WithdrawDialog_Title', N'あなたはBTCを引き出しようとする。');
INSERT INTO MobileLangDetail VALUES (1, N'WithdrawDialog_Validate_Address', N'Please input BTC address');INSERT INTO MobileLangDetail VALUES(2, N'WithdrawDialog_Validate_Address', N'BTCアドレスを入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'WithdrawDialog_Validate_Amount_Max', N'Please input number BTC smaller than user BTC amount');INSERT INTO MobileLangDetail VALUES(2, N'WithdrawDialog_Validate_Amount_Max', N'BTC額より小さいBTC金額を入力してください');
INSERT INTO MobileLangDetail VALUES (1, N'WithdrawDialog_Validate_Amount_Min', N'The number of BTC amount always greater than 0');INSERT INTO MobileLangDetail VALUES(2, N'WithdrawDialog_Validate_Amount_Min', N'BTC金額は0より大きい。');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_Input_Confirm_Password_Placeholder', N'Confirm password');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_Input_Confirm_Password_Placeholder', N'パスワードを認証する');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_Input_Current_Password_Placeholder', N'Current password');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_Input_Current_Password_Placeholder', N'現在のパスワード');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_Validate_Confirm_Password_Not_Match', N'Password not match');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_Validate_Confirm_Password_Not_Match', N'パスワードが一致しません');
INSERT INTO MobileLangDetail VALUES (1, N'EditPasswordScreen_Validate_Current_Password_Not_Match', N'Password current not match');INSERT INTO MobileLangDetail VALUES(2, N'EditPasswordScreen_Validate_Current_Password_Not_Match', N'現在のパスワードと一致しないパスワード');
