USE CPL;

INSERT INTO LangDetail Values (1, N'Affiliate', N'Affiliate');
INSERT INTO LangDetail Values (2, N'Affiliate', N'アフェリエイト');
INSERT INTO LangDetail Values (1, N'StandardAffiliate', N'Standard Affiliate');
INSERT INTO LangDetail Values (2, N'StandardAffiliate', N'アフェリエイトユーザ');
INSERT INTO LangDetail Values (1, N'AgencyAffiliate', N'Agency Affiliate');
INSERT INTO LangDetail Values (2, N'AgencyAffiliate', N'代理店アフィリエイト');
INSERT INTO LangDetail Values (1, N'Today', N'Today');
INSERT INTO LangDetail Values (2, N'Today', N'今日');
INSERT INTO LangDetail Values (1, N'Yesterday', N'Yesterday');
INSERT INTO LangDetail Values (2, N'Yesterday', N'昨日');
INSERT INTO LangDetail Values (1, N'Links', N'Links');
INSERT INTO LangDetail Values (2, N'Links', N'リンク');
INSERT INTO LangDetail Values (1, N'Slider', N'Slider');
INSERT INTO LangDetail Values (2, N'Slider', N'スライダー');
INSERT INTO LangDetail Values (1, N'LotteryGame', N'Lottery Game');
INSERT INTO LangDetail Values (2, N'LotteryGame', N'仮想通貨くじ');
INSERT INTO LangDetail Values (1, N'Banner', N'Banner');
INSERT INTO LangDetail Values (2, N'Banner', N'バナー');
INSERT INTO LangDetail Values (1, N'Setting', N'Setting');
INSERT INTO LangDetail Values (2, N'Setting', N'設定');
INSERT INTO LangDetail Values (1, N'KYCVerificationActivated', N'KYC verification activated');
INSERT INTO LangDetail Values (2, N'KYCVerificationActivated', N'KYC認証が完了しました');
INSERT INTO LangDetail Values (1, N'StandardAffiliateTiers', N'Standard Affiliate Tiers');
INSERT INTO LangDetail Values (2, N'StandardAffiliateTiers', N'標準アフィリエイトティア');
INSERT INTO LangDetail Values (1, N'AgencyAffiliateTiers', N'Agency Affiliate Tiers');
INSERT INTO LangDetail Values (2, N'AgencyAffiliateTiers', N'代理店アフィリエイトティア');
INSERT INTO LangDetail Values (1, N'CookieExpiredInDays', N'Cookie Expired in Days');
INSERT INTO LangDetail Values (2, N'CookieExpiredInDays', N'Cookieの有効期限');
INSERT INTO LangDetail Values (1, N'AccountActivationEnable', N'Account activation enable');
INSERT INTO LangDetail Values (2, N'AccountActivationEnable', N'アカウントアクティベーション有効');
INSERT INTO LangDetail Values (1, N'AgencyCommissionDirectSaleTier1', N'Commission of direct introduction of TIER 1​');
INSERT INTO LangDetail Values (2, N'AgencyCommissionDirectSaleTier1', N'ティア1の直接紹介コミッション');
INSERT INTO LangDetail Values (1, N'AgencyCommissionDirectSaleTier2', N'Commission of direct introduction of TIER 2');
INSERT INTO LangDetail Values (2, N'AgencyCommissionDirectSaleTier2', N'ティア2の直接紹介コミッション');
INSERT INTO LangDetail Values (1, N'AgencyCommissionDirectSaleTier3', N'Commission of direct introduction of TIER 3');
INSERT INTO LangDetail Values (2, N'AgencyCommissionDirectSaleTier3', N'ティア3の直接紹介コミッション');
INSERT INTO LangDetail Values (1, N'AgencyCommissionTier2SaleToTier1', N'Commission of TIER 2 sales received by TIER 1​');
INSERT INTO LangDetail Values (2, N'AgencyCommissionTier2SaleToTier1', N'ティア1が受け取ったティア2からのコミッション');
INSERT INTO LangDetail Values (1, N'AgencyCommissionTier3SaleToTier1', N'Commission of TIER 3 sales received by TIER 1');
INSERT INTO LangDetail Values (2, N'AgencyCommissionTier3SaleToTier1', N'ティア1が受け取ったティア3からのコミッション');
INSERT INTO LangDetail Values (1, N'AgencyCommissionTier3SaleToTier2', N'Commission of TIER 3 sales received by TIER 2​');
INSERT INTO LangDetail Values (2, N'AgencyCommissionTier3SaleToTier2', N'ティア2が受け取ったティア3からのコミッション');
INSERT INTO LangDetail Values (1, N'StandardCommissionTier1', N'Tier 1 Commission​');
INSERT INTO LangDetail Values (2, N'StandardCommissionTier1', N'ティア1のコミッション');
INSERT INTO LangDetail Values (1, N'StandardCommissionTier2', N'Tier 2 Commission​');
INSERT INTO LangDetail Values (2, N'StandardCommissionTier2', N'ティア2のコミッション');
INSERT INTO LangDetail Values (1, N'StandardCommissionTier3', N'Tier 3 Commission​');
INSERT INTO LangDetail Values (2, N'StandardCommissionTier3', N'ティア3のコミッション');
INSERT INTO LangDetail Values (1, N'On', N'On');
INSERT INTO LangDetail Values (2, N'On', N'オン');
INSERT INTO LangDetail Values (1, N'Off', N'Off​');
INSERT INTO LangDetail Values (2, N'Off', N'オフ');
INSERT INTO LangDetail Values (1, N'BecomeAnAffiliate', N'Do you want to become an affiliate?');
INSERT INTO LangDetail Values (2, N'BecomeAnAffiliate', N'あなたは、アフィリエイトに参加しますか？');
INSERT INTO LangDetail Values (1, N'Join', N'Join');
INSERT INTO LangDetail Values (2, N'Join', N'参加');
INSERT INTO LangDetail Values (1, N'Affiliate', N'Affiliate');
INSERT INTO LangDetail Values (2, N'Affiliate', N'アフィリエイト');
INSERT INTO LangDetail Values (1, N'AffiliateApplicationReceived', N'We have received your affiliate application, please wait for our update.  ');
INSERT INTO LangDetail Values (2, N'AffiliateApplicationReceived', N'あなたのアフィリエイトの申し込みを受け付けました。更新までしばらくお待ちください。');
INSERT INTO LangDetail Values (1, N'AffiliateApplicationApproved', N'Your affiliate application is approved.');
INSERT INTO LangDetail Values (2, N'AffiliateApplicationApproved', N'あなたのアフィリエイトの申し込みは承認されました。');
INSERT INTO LangDetail Values (1, N'Approved', N'Approved');
INSERT INTO LangDetail Values (2, N'Approved', N'承認済み');
INSERT INTO LangDetail Values (1, N'KYCRequiredBeforeAffiliate', N'Please <a href=''/Profile/Kyc''>verify your KYC</a> before submitting affiliate application');	
INSERT INTO LangDetail Values (2, N'KYCRequiredBeforeAffiliate', N'アフィリエイトプログラムに応募する前に、<a href=''/Profile/Kyc''>KYCを提出</a>してください');
INSERT INTO LangDetail Values (1, N'NotJoinedYet', N'not joined yet.');
INSERT INTO LangDetail Values (2, N'NotJoinedYet', N'参加していません。');
INSERT INTO LangDetail Values (1, N'ClickHereToChangeAffiliate', N'Click <a href="/Profile/Affiliate" class="text-primary">here</a> to change.');
INSERT INTO LangDetail Values (2, N'ClickHereToChangeAffiliate', N'変更は <a href="/Profile/Affiliate" class="text-primary">ココ</a> をクリックしてください。');
INSERT INTO LangDetail Values (1, N'AffiliateApplicationSubmitted', N'Your affiliate application is submitted successfully.');
INSERT INTO LangDetail Values (2, N'AffiliateApplicationSubmitted', N'あなたの申し込みは完了しました。');
INSERT INTO LangDetail Values (1, N'AgencyAffiliateURLGenerated', N'Agency affiliate url is generated successfully.');
INSERT INTO LangDetail Values (2, N'AgencyAffiliateURLGenerated', N'代理店のアフィリエイトのURLが正常に生成されました。');
INSERT INTO LangDetail Values (1, N'AgencyURLGenerator', N'Agency URL Generator');
INSERT INTO LangDetail Values (2, N'AgencyURLGenerator', N'代理店URL生成');
INSERT INTO LangDetail Values (1, N'AgencyURLGeneratorDesc', N'Please specify how many days that this URL will be expired.');
INSERT INTO LangDetail Values (2, N'AgencyURLGeneratorDesc', N'このURLの有効日数を指定してください。');
INSERT INTO LangDetail Values (1, N'ExpiredDayFromNow', N'Number of days from now');
INSERT INTO LangDetail Values (2, N'ExpiredDayFromNow', N'今からの日数');
INSERT INTO LangDetail Values (1, N'NumberOfDaysRequired', N'Please fill in number of days');
INSERT INTO LangDetail Values (2, N'NumberOfDaysRequired', N'日数を記入してください');
INSERT INTO LangDetail Values (1, N'Generate', N'Generate');
INSERT INTO LangDetail Values (2, N'Generate', N'生成する');
INSERT INTO LangDetail Values (1, N'UrlGenerated', N'URL generated');
INSERT INTO LangDetail Values (2, N'UrlGenerated', N'生成されたURL');
INSERT INTO LangDetail Values (1, N'AffiliateApprove', N'Affiliate approve');
INSERT INTO LangDetail Values (2, N'AffiliateApprove', N'アフィリエイト承認');
INSERT INTO LangDetail Values (1, N'Approve', N'Approve');
INSERT INTO LangDetail Values (2, N'Approve', N'承認する');
INSERT INTO LangDetail Values (1, N'ListOfAffiliateApplication', N'List of affiliate application');
INSERT INTO LangDetail Values (2, N'ListOfAffiliateApplication', N'アフィリエイト申込一覧');
INSERT INTO LangDetail Values (1, N'ApplicationArePending', N'applications are pending');
INSERT INTO LangDetail Values (2, N'ApplicationArePending', N'アプリケーションは保留中です');
INSERT INTO LangDetail Values (1, N'AffiliateApplication', N'Affiliate application');
INSERT INTO LangDetail Values (2, N'AffiliateApplication', N'アフィリエイト申込');
INSERT INTO LangDetail Values (1, N'AffiliateApprovedDescription', N'Congratulation, your affiliate application is approved.');
INSERT INTO LangDetail Values (2, N'AffiliateApprovedDescription', N'おめでとう、あなたのアフィリエイト申込が承認されました。');
INSERT INTO LangDetail Values (1, N'AffiliateIsApproved', N'Affiliate application is approved successfully.');
INSERT INTO LangDetail Values (2, N'AffiliateIsApproved', N'アフィリエイト申込が正常に承認されました。');
INSERT INTO LangDetail Values (1, N'AffiliateHasBeenApproved', N'Affiliate application has been approved.');
INSERT INTO LangDetail Values (2, N'AffiliateHasBeenApproved', N'アフィリエイト申込が承認されました。');
INSERT INTO LangDetail Values (1, N'AffliateUrl', N'Affiliate URL');
INSERT INTO LangDetail Values (2, N'AffliateUrl', N'アフィリエイトURL');
INSERT INTO LangDetail Values (1, N'InvalidOrExpiredAgencyToken', N'Invalid or expired agency token.');
INSERT INTO LangDetail Values (2, N'InvalidOrExpiredAgencyToken', N'無効または期限切れの代理店トークン');
INSERT INTO LangDetail Values (1, N'TotalCPLUsed', N'Total CPL Used');
INSERT INTO LangDetail Values (2, N'TotalCPLUsed', N'使用された総CPL');
INSERT INTO LangDetail Values (1, N'TotalCPLAwarded', N'Total CPL Awarded');
INSERT INTO LangDetail Values (2, N'TotalCPLAwarded', N'合計CPL賞');
INSERT INTO LangDetail Values (1, N'AffiliateProgram', N'Affiliate program');
INSERT INTO LangDetail Values (2, N'AffiliateProgram', N'アフィリエイトプログラム');
INSERT INTO LangDetail Values (1, N'IsKYCVerificationActivated', N'Is KYC verification activated?');
INSERT INTO LangDetail Values (2, N'IsKYCVerificationActivated', N'KYC確認は有効になっていますか？');
INSERT INTO LangDetail Values (1, N'Authentication', N'Authentication');
INSERT INTO LangDetail Values (2, N'Authentication', N'認証');
INSERT INTO LangDetail Values (1, N'StandardCommissionTier1Required', N'Please fill in tier 1 commission rate');
INSERT INTO LangDetail Values (2, N'StandardCommissionTier1Required', N'ティア1の報酬パーセンテージをご記入ください(Standard)');
INSERT INTO LangDetail Values (1, N'StandardCommissionTier2Required', N'Please fill in tier 2 commission rate');
INSERT INTO LangDetail Values (2, N'StandardCommissionTier2Required', N'ティア2の報酬パーセンテージをご記入ください(Standard)');
INSERT INTO LangDetail Values (1, N'StandardCommissionTier3Required', N'Please fill in tier 3 commission rate');
INSERT INTO LangDetail Values (2, N'StandardCommissionTier3Required', N'ティア3の報酬パーセンテージをご記入ください(Standard)');
INSERT INTO LangDetail Values (1, N'AgencyCommissionDirectSaleTier1Required', N'Please fill in tier 1 commission rate');
INSERT INTO LangDetail Values (2, N'AgencyCommissionDirectSaleTier1Required', N'ティア1の報酬パーセンテージをご記入ください(Agency)');
INSERT INTO LangDetail Values (1, N'AgencyCommissionDirectSaleTier2Required', N'Please fill in tier 2 commission rate');
INSERT INTO LangDetail Values (2, N'AgencyCommissionDirectSaleTier2Required', N'ティア2の報酬パーセンテージをご記入ください(Agency)');
INSERT INTO LangDetail Values (1, N'AgencyCommissionDirectSaleTier3Required', N'Please fill in tier 3 commission rate');
INSERT INTO LangDetail Values (2, N'AgencyCommissionDirectSaleTier3Required', N'ティア3の報酬パーセンテージをご記入ください(Agency)');
INSERT INTO LangDetail Values (1, N'AgencyCommissionTier2SaleToTier1Required', N'Please fill in commission of tier 2 sales received by tier 1');
INSERT INTO LangDetail Values (2, N'AgencyCommissionTier2SaleToTier1Required', N'ティア1が受け取るティア2のコミッションを記入してください');
INSERT INTO LangDetail Values (1, N'AgencyCommissionTier3SaleToTier1Required', N'Please fill in commission of tier 3 sales received by tier 1');
INSERT INTO LangDetail Values (2, N'AgencyCommissionTier3SaleToTier1Required', N'ティア1が受け取るティア3のコミッションを記入してください');
INSERT INTO LangDetail Values (1, N'AgencyCommissionTier3SaleToTier2Required', N'Please fill in commission of tier 3 sales received by tier 2');
INSERT INTO LangDetail Values (2, N'AgencyCommissionTier3SaleToTier2Required', N'ティア2が受け取るティア3のコミッションを記入してください');
INSERT INTO LangDetail Values (1, N'Cookie', N'Cookie');
INSERT INTO LangDetail Values (2, N'Cookie', N'Cookie');
INSERT INTO LangDetail Values (1, N'CookieExpirationsRequired', N'Please input value for days when cookies is expired');
INSERT INTO LangDetail Values (2, N'CookieExpirationsRequired', N'Cookieが期限切れになった日の値を入力してください');
INSERT INTO LangDetail Values (1, N'Open', N'Open');
INSERT INTO LangDetail Values (2, N'Open', N'開く');
INSERT INTO LangDetail Values (1, N'Close', N'Close');
INSERT INTO LangDetail Values (2, N'Close', N'閉じる');
INSERT INTO LangDetail Values (1, N'BTCPricePredictionChartTitle', N'Live BTC/USDT rate');
INSERT INTO LangDetail Values (2, N'BTCPricePredictionChartTitle', N'ライブBTC/USDTレート');
INSERT INTO LangDetail Values (1, N'BTCPricePredictionSeriesName', N'BTC/USDT rate');
INSERT INTO LangDetail Values (2, N'BTCPricePredictionSeriesName', N'BTC/USDTレート');
INSERT INTO LangDetail Values (1, N'ListOfStandardAffiliate', N'List Of Standard Affiliate');
INSERT INTO LangDetail Values (2, N'ListOfStandardAffiliate', N'標準アフィリエイトのリスト');
INSERT INTO LangDetail Values (1, N'ListOfStandardAffiliate', N'List Of Standard Affiliate');
INSERT INTO LangDetail Values (2, N'ListOfStandardAffiliate', N'標準アフィリエイトのリスト');
INSERT INTO LangDetail Values (1, N'TotalSaleInCPL', N'Total sale in CPL');
INSERT INTO LangDetail Values (2, N'TotalSaleInCPL', N'CPLでの総販売額');
INSERT INTO LangDetail Values (1, N'TotalIntroducer', N'Total introducer');
INSERT INTO LangDetail Values (2, N'TotalIntroducer', N'トータルイントロデューサ');
INSERT INTO LangDetail Values (1, N'AffiliateCreatedDate', N'Affiliate created date');
INSERT INTO LangDetail Values (2, N'AffiliateCreatedDate', N'アフィリエイト作成日');
INSERT INTO LangDetail Values (1, N'Tier1', N'Tier 1');
INSERT INTO LangDetail Values (2, N'Tier1', N'ティア 1');
INSERT INTO LangDetail Values (1, N'Tier2', N'Tier 2');
INSERT INTO LangDetail Values (2, N'Tier2', N'ティア 2');
INSERT INTO LangDetail Values (1, N'Tier3', N'Tier 3');
INSERT INTO LangDetail Values (2, N'Tier3', N'ティア 3');
INSERT INTO LangDetail Values (1, N'Lock', N'Lock');
INSERT INTO LangDetail Values (2, N'Lock', N'ロック');
INSERT INTO LangDetail Values (1, N'UnLock', N'UnLock');
INSERT INTO LangDetail Values (2, N'UnLock', N'アンロック');
INSERT INTO LangDetail Values (1, N'LockSuccessful', N'Lock Successful');
INSERT INTO LangDetail Values (2, N'LockSuccessful', N'ロック成功');
INSERT INTO LangDetail Values (1, N'UnLockSuccessful', N'Unlock Successful');
INSERT INTO LangDetail Values (2, N'UnLockSuccessful', N'成功したロック解除');
