select * from LangDetail where Name like 'MessageSentSuccessfully';

insert into LangDetail values (1, N'Contact', N'Contact');
insert into LangDetail values (2, N'Contact', N'接触');
insert into LangDetail values (1, N'Submit', N'Submit');
insert into LangDetail values (2, N'Submit', N'提出する');
insert into LangDetail values (1, N'Support', N'Support');
insert into LangDetail values (2, N'Support', N'サポート');
insert into LangDetail values (1, N'CategoryIsRequired', N'Category is required');
insert into LangDetail values (2, N'CategoryIsRequired', N'カテゴリは必須です');
insert into LangDetail values (1, N'Description', N'Description');
insert into LangDetail values (2, N'Description', N'説明');
insert into LangDetail values (1, N'Subject', N'Subject');
insert into LangDetail values (2, N'Subject', N'件名');
insert into LangDetail values (1, N'SubjectIsRequired', N'Subject is required');
insert into LangDetail values (2, N'SubjectIsRequired', N'件名は必須です');
insert into LangDetail values (1, N'Category', N'Category');
insert into LangDetail values (2, N'Category', N'カテゴリー');
insert into LangDetail values (1, N'EmailIsRequired', N'Email is required');
insert into LangDetail values (2, N'EmailIsRequired', N'メールが必要です');
insert into LangDetail values (1, N'DescriptionIsRequired', N'Description is required');
insert into LangDetail values (2, N'DescriptionIsRequired', N'説明が必要です');
insert into LangDetail values (1, N'AskUsAnything', N'Ask us anything');
insert into LangDetail values (2, N'AskUsAnything', N'私たちに何か質問する');
insert into LangDetail values (1, N'CPLTeam', N'CPL Team');
insert into LangDetail values (2, N'CPLTeam', N'CPLチーム');
insert into LangDetail values (1, N'ThankYouForYourContactMessage', N'Thank you, your message is sent successfully. We will get in touch soon.');
insert into LangDetail values (2, N'ThankYouForYourContactMessage', N'ありがとう、あなたのメッセージは正常に送信されます。 私たちはすぐに連絡を取ります。');
insert into LangDetail values (1, N'MessageSentSuccessfully', N'Message is sent successfully');
insert into LangDetail values (2, N'MessageSentSuccessfully', N'メッセージが正常に送信されました');